lista = input("Introduce una lista de palabras separadas por coma\n")
lista_separada = lista.split(", ")
lista_sin_duplicados = set(lista_separada)
lista_del_set = list(lista_sin_duplicados)
lista_del_set.sort()
print(lista_del_set)
